name: Pull Request
on:
  pull_request:
    branches:
      - main
      - beta

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  ARCHITECTURES: linux/amd64,linux/arm64

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into Docker
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: ${{ env.ARCHITECTURES }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.0
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build and Push Docker Images
        run: |
          source version.env
          DOCKER_IMAGE=ci4rail/dev-edgefarm-nats
          docker buildx build \
             -f Dockerfile \
             --push \
             --platform ${ARCHITECTURES} \
             --build-arg NATS_LEAFNODE_REGISTRY_VERSION=${NATS_LEAFNODE_REGISTRY_VERSION} \
             --build-arg NATS_SERVER_VERSION=${NATS_SERVER_VERSION} \
             -t ${DOCKER_IMAGE}:${GITHUB_SHA::8} \
             -t ${DOCKER_IMAGE}:latest .
